version: "3.7"

services:
  web:
    image: gaana-api
    depends_on:
      - db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Safwan@2
      POSTGRES_DATABASE: peak
      POSTGRES_HOST: host.docker.internal
    ports:
      - "5000:5000"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Safwan@2
      POSTGRES_USER: postgres
      POSTGRES_DB: peak
    ports:
      - "5432:5432"