version: "3.7"

services:
  web:
    build: .
    depends_on:
      - db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Safwanman@2
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
    ports:
      - "5000:5000"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Safwanman@2
    volumes: 
      - ./postgres-data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
